#! /bin/sh

xrandr --output DP-1 --mode 1920x1080 --rate 240 --primary --output eDP-1 --off &

pgrep -x sxhkd > /dev/null || sxhkd &

	bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'
#bspc config left_padding 79
#bspc config right_padding 2
bspc config window_gap 30
#bspc config top_padding 3
#bspc config bottom_padding 2

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config normal_border_color "#BAC2DE"
bspc config focused_border_color "#89B4FA"

polybar -r &
#eww daemon &
#eww open bar &
feh --bg-max /home/fwuffy/wallpapers/images/em-rofi.webp & 
xrdb -merge .Xresources &
picom &
dunst &
#xrandr --output DP-1 --mode 1920x1080 --rate 240 --primary --output eDP-1 --off &
pipewire &
$HOME/.config/bspwm/scripts/lock
